# Generated by Django 5.2 on 2025-08-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
